# 定义端口号
server:
  port: 8092
# 配置数据源
spring:
  datasource:
    druid:
      username: root
      password: 28dqmGY#
      url: jdbc:mysql://101.200.137.108:3306/db3?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.jdbc.Driver
      # 初始化时建立物理连接的个数。初始化发生在显示调用 init 方法，或者第一次 getConnection 时
      initialSize: 6
      # 最小连接池数量
      minIdle: 2
      # 最大连接池数量
      maxActive: 20
      # 获取连接时最大等待时间，单位毫秒。配置了 maxWait 之后，缺省启用公平锁，
      # 并发效率会有所下降，如果需要可以通过配置 useUnfairLock 属性为 true 使用非公平锁。
      maxWait: 60000
#      profiles:
#        active:cache,stock
# 配置mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印运行的sql
  type-aliases-package: com.itheima.stock.pojo.entity # 批量给指定包下的实体类取别名，方便xml使用，默认是类名，首字母小写
  mapper-locations: classpath:mapper/*.xml # 加载类路径下的mapper下的所有xml文件
# 设置分页
pagehelper:
  helper-dialect: mysql #指定分页数据库类型（方言）
  reasonable: true #合理查询超过最大页，则查询最后一页

# 配置股票相关的参数
stock:
  inner: # A股
    - sh000001 # 上证ID
    - sz399001 #  深证ID
  outer: # 外盘
    - int_dji # 道琼斯
    - int_nasdaq # 纳斯达克
    - int_hangseng # 恒生
    - int_nikkei # 日经指数
    - b_FSSTI # 新加坡
  marketUrl: https://hq.sinajs.cn/list=
  blockUrl: http://vip.stock.finance.sina.com.cn/q/view/newSinaHy. php
  # 设置分页
  pagehelper:
    helper-dialect: mysql #指定分页数据库类型（方言）
    reasonable: true #合理查询超过最大页，则查询最后一页

